apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      serviceAccountName: website
      containers:
      - name: website
        image: eu.gcr.io/flavour101-images/website:v0
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 80
        resources:
          requests:
            memory: 0.2Gi
            cpu: 500m
          limits:
            memory: 0.5Gi
            cpu: "1"
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 60
          httpGet:
            port: 80
            path: /
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
