apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: {{.KUBE_NAMESPACE}}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{.DOMAIN_EMAIL}}
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - selector:
          dnsZones:
            - "flavour101.com"
        dns01:
          route53:
            region: eu-west-1
            hostedZoneID: {{.HOSTED_ZONE_ID}}
            accessKeyID: {{.ROUTE53_ACCESS_KEY_ID}}
            secretAccessKeySecretRef:
              name: cert-manager-route53
              key: secret-access-key
