apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend
  namespace: {{.KUBE_NAMESPACE}}
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: frontend
        env: {{.KUBE_NAMESPACE}}
    spec:
      containers:
      - name: frontend
        image: "{{.IMAGE_TAG}}"
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: "0.05Gi"
            cpu: "0.008"
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 60
          httpGet:
            port: 80
            path: /